# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(412, 291)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.selectFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectFileButton.setGeometry(QtCore.QRect(0, 0, 191, 291))
        self.selectFileButton.setObjectName("selectFileButton")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(190, 0, 217, 291))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.kincaid = QtWidgets.QLabel(self.layoutWidget)
        self.kincaid.setObjectName("kincaid")
        self.verticalLayout_2.addWidget(self.kincaid)
        self.ari = QtWidgets.QLabel(self.layoutWidget)
        self.ari.setObjectName("ari")
        self.verticalLayout_2.addWidget(self.ari)
        self.coleman = QtWidgets.QLabel(self.layoutWidget)
        self.coleman.setObjectName("coleman")
        self.verticalLayout_2.addWidget(self.coleman)
        self.flesh = QtWidgets.QLabel(self.layoutWidget)
        self.flesh.setObjectName("flesh")
        self.verticalLayout_2.addWidget(self.flesh)
        self.gunning = QtWidgets.QLabel(self.layoutWidget)
        self.gunning.setObjectName("gunning")
        self.verticalLayout_2.addWidget(self.gunning)
        self.lix = QtWidgets.QLabel(self.layoutWidget)
        self.lix.setObjectName("lix")
        self.verticalLayout_2.addWidget(self.lix)
        self.smog = QtWidgets.QLabel(self.layoutWidget)
        self.smog.setObjectName("smog")
        self.verticalLayout_2.addWidget(self.smog)
        self.rix = QtWidgets.QLabel(self.layoutWidget)
        self.rix.setObjectName("rix")
        self.verticalLayout_2.addWidget(self.rix)
        self.dale = QtWidgets.QLabel(self.layoutWidget)
        self.dale.setObjectName("dale")
        self.verticalLayout_2.addWidget(self.dale)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.selectFileButton.setText(_translate("MainWindow", "Select File"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:14pt; font-weight:600;\">Kincaid:</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:14pt; font-weight:600;\">ARI:</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:14pt; font-weight:600;\">Coleman-Liau:</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:14pt; font-weight:600;\">FleschReadingEase:</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:14pt; font-weight:600;\">GunningFogIndex:</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:14pt; font-weight:600;\">LIX:</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:14pt; font-weight:600;\">SMOGIndex:</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:14pt; font-weight:600;\">RIX:</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:14pt; font-weight:600;\">DaleChallIndex:</span></p></body></html>"))
        self.kincaid.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\"></span></p></body></html>"))
        self.ari.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\"></span></p></body></html>"))
        self.coleman.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\"></span></p></body></html>"))
        self.flesh.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\"></span></p></body></html>"))
        self.gunning.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\"></span></p></body></html>"))
        self.lix.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\"></span></p></body></html>"))
        self.smog.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\"></span></p></body></html>"))
        self.rix.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\"></span></p></body></html>"))
        self.dale.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\"></span></p></body></html>"))
